### ISSUE TITLE
Classifier Weights

### ISSUE THREAD

**Issue by hellerguyh** [janghyuncho/DECOLA#11]
Hey,

Thank you for the fascinating and excellent work.

I have a question regarding the code in your repository. I noticed that the classifier weights are loaded from existing files, such as `datasets/metadata/lvis_v1_clip_a+cname.npy`. Does this mean that these weights were optimized as part of the training procedure, or are they equivalent to the CLIP embeddings of the corresponding texts?

Thanks

**Comment by janghyuncho** [comment]
Sorry for late reply! They are just clip embedding (never trained).

**Comment by hellerguyh** [comment]
> Sorry for late reply! They are just clip embedding (never trained).

Thank you for the response
