### ISSUE TITLE
missing metadata

### ISSUE THREAD

**Issue by Noietch** [janghyuncho/DECOLA#2]
Your work is excellent. When I was running the first phase of training, I found that the file datasets/metadata/lvis_v1_clip_a+object.npy was missing. Could you provide it? I look forward to your reply.

**Comment by janghyuncho** [comment]
Thank you for your interest in DECOLA! 

I updated the necessary metadata [here](https://github.com/janghyuncho/DECOLA/tree/main/datasets/metadata). My apologies, some of the files may be missing at the moment. I will update it very soon. 

Thank you!
