### ISSUE TITLE
missing something

### ISSUE THREAD

**Issue by SteveTaoTao** [janghyuncho/DECOLA#3]
../../LVDETR/third_party/CenterNet2/
and  requirements.txt

**Comment by janghyuncho** [comment]
Hello SteveTaoTao, 

Thank you for pointing out missing files! I just updated [third_party/](https://github.com/janghyuncho/DECOLA/tree/main/third_party) and [requirements.txt](https://github.com/janghyuncho/DECOLA/blob/main/requirements.txt). Hope this resolves the issue!
