### ISSUE TITLE
SwinL-Phase2 Weights seems empty.

### ISSUE THREAD

**Issue by trarynight** [janghyuncho/DECOLA#4]
Thanks for your excellent work. I want using the best swinl-phase2 open-vocabulary models to test some images. However i found the model_zoo link seems empty. Would you provide it? thanks.

**Comment by janghyuncho** [comment]
Hello, thank you for your interest in our work and sorry for the late reply. 

The missing model weights are updated now in the [model_zoo page](https://github.com/janghyuncho/DECOLA/blob/main/docs/MODEL_ZOO.md).

**Comment by trarynight** [comment]
thanks.
