### ISSUE TITLE
What is the difference between baseline and DECOLA phase 1?

### ISSUE THREAD

**Issue by Dwrety** [janghyuncho/DECOLA#5]
What is the difference between baseline and DECOLA phase 1?

**Comment by janghyuncho** [comment]
Sorry for delayed response. The difference between baseline and DECOLA phase 1 is best illustrated in [here](https://github.com/janghyuncho/DECOLA/blob/main/docs/TRAINING.md#highlights), or in page 6 of our paper. 

To highlight the difference, "baseline" trains as a standard object detector for multi-class objective with DeformableDETR architecture, except we replace the final classification layer with CLIP text embedding. In DECOLA Phase 1, we condition object detection pipeline with text and train each conditioned detection with binary objective. 

Hope this explanation helps.
