### ISSUE TITLE
Can not reproduce Direct zero-shot transfer to LVIS v1.0 results

### ISSUE THREAD

**Issue by fushh** [janghyuncho/DECOLA#9]
command: python train_net.py --num-gpus 4 --config-file configs/DECOLA_PHASE2_O365IN21k_CLIP_SwinT.yaml --eval-only MODEL.WEIGHTS DECOLA_PHASE2_O365IN21k_CLIP_SwinT.pth

there are several errors:
1. there is no config named `DECOLA_PHASE1_O365_CLIP_SwinT_4x.yaml`
2. there are some redundant config items: `NO_FED_LOSS_LIST`, `ONLINE_LABELING`

I try to fix the problems by renaming the file to `DECOLA_PHASE1_O365_CLIP_SwinT.yaml` and deleting the config items. It works but with poor inference results.
![image](https://github.com/janghyuncho/DECOLA/assets/71886569/f3b32d4e-ccc0-4fe4-add2-1fd29492a898)

Looking forward to your help.

**Comment by janghyuncho** [comment]
Hello, I am sorry for the late response! The evaluation configs have been updated. In short, AP_fixed metric needs some special setting [here](https://github.com/janghyuncho/DECOLA/tree/main/configs/eval) to be  careful with. My apologies!
